### ISSUE TITLE
USS unit warnings on import

### ISSUE THREAD

**Issue by ptbarnaby** [neon-age/Smart-Hierarchy#11]
Shows numerous warnings on import (Unity 2020.1.14f1), e.g. 

`StyleSheet import: type=Validation, code=InvalidProperty file=Packages/com.av.smart-hierarchy/UI/preferences-style.uss:3
    Expected (<length> | <percentage>) but found '6'
    padding-left: 6 -> Property expects a unit. Did you forget to add px or %?
`

`StyleSheet import: type=Validation, code=InvalidProperty file=Packages/com.av.smart-hierarchy/UI/popup-window.uss:21
    Unknown property '-unity-slice' (did you mean '-unity-slice-top'?)
    -unity-slice: 1
`

**Comment by neon-age** [comment]
I just noticed that there is "Disable Validation" toggle on StyleSheet assets. They won't bother you anymore 🙂
