### ISSUE TITLE
Warning: No script asset for HierarchyPreferences. Check that the definition is in a file of the same name.

### ISSUE THREAD

**Issue by Thane5** [neon-age/Smart-Hierarchy#18]
This warning regularly pops up when i enter playmode: 
`No script asset for HierarchyPreferences. Check that the definition is in a file of the same name.`

**Comment by Thane5** [comment]
I have no idea why i get this issue, but since this only appears in projects that have this addon installed, i guessed that it would be related to this.
[](url)
![Screenshot 2021-02-25 150207](https://user-images.githubusercontent.com/13683581/109164229-78b86d00-777a-11eb-95a0-89cd1af49fe3.png)

**Comment by neon-age** [comment]
This should fix the issue

**Comment by Thane5** [comment]
I haven't seen the warning since i updated to this revision, looks like it works
