### ISSUE TITLE
Multiple Warnings during Play

### ISSUE THREAD

**Issue by Thane5** [neon-age/Smart-Hierarchy#2]
I'm working with Bolt on UI elements for my game, and some of the canvas elements seem to cause warning messages like this:

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
UnityEngine.Transform:set_parent(Transform)
AV.Hierarchy.DetachOnBuildProcess:OnProcessScene(Scene, BuildReport) (at Library/PackageCache/com.av.smart-hierarchy@5a8cc0892c/Base/DetachOnBuildProcess.cs:45)
UnityEditor.Build.BuildPipelineInterfaces:OnSceneProcess(Scene, BuildReport)

**Comment by neon-age** [comment]
Changed to SetParent method and also reparenting to folder's parent instead of scene root.

**Comment by Thane5** [comment]
Tested in my scene, seems to work now.
