### ISSUE TITLE
Any ways to remove serialization errors on builds?

### ISSUE THREAD

**Issue by VirsabiMunk** [neon-age/Smart-Hierarchy#29]
I get these warnings for each Hierarchy Collection in my WebGL build;

`A scripted object (probably AV.Hierarchy.Collection?) has a different serialization layout when loading. (Read 32 bytes but expected 40 bytes) Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?`
Followed by warning;
`The referenced script on this Behaviour (Game Object '*GOName*') is missing!`

Normally I would just ignore these, but as it's WebGL it seems to create other issues down the line.

**Comment by neon-age** [comment]
Oh, seems like I forgot to strip Collection components from build.

> but as it's WebGL it seems to create other issues down the line.

What kind of issues you think it causes?

**Comment by VirsabiMunk** [comment]
> Oh, seems like I forgot to strip Collection components from build.
> 
> > but as it's WebGL it seems to create other issues down the line.
> 
> What kind of issues you think it causes?

I am doing a WebGL WebXR demo using De-Panther's extension and found some [issues](https://github.com/De-Panther/unity-webxr-export/issues/141) that we for now only can track to these warnings/errors - I am digging a bit more, but it is most likely unrelated issues.

**Comment by neon-age** [comment]
Pushed a commit, can you try it from master?

**Comment by neon-age** [comment]
I also noticed another issue with _disabled_ collections that have unchecked 'Keep Transform' - their children are not being stripped

**Comment by VirsabiMunk** [comment]
> Pushed a commit, can you try it from master?

Confirmed - All good now :)

**Comment by neon-age** [comment]
The fix and forementioned stripping change are available in 0.3.1-pre.9 now
