### ISSUE TITLE
[Fixed] Critical Build Errors

### ISSUE THREAD

**Issue by Thane5** [neon-age/Smart-Hierarchy#4]
I tried building for x64 Windows, but got 7 Errors that would prevent it. 

The error message was always a variation of this:

`Library\PackageCache\com.av.smart-hierarchy@94113c3d21\Base\HierarchySettingsProvider.cs(8,26): error CS0234: The type or namespace name 'EditorGUI' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`

After removing Smart Hierarchy the build process did complete as it should.

Screenshot of the Console:
![Screenshot 2020-11-11 182659](https://user-images.githubusercontent.com/13683581/98843622-81936600-244b-11eb-8251-2c6db9e2a772.png)

**Comment by neon-age** [comment]
I wrote in pull request the reasoning behind this problem.

**Comment by neon-age** [comment]
I wrote in pull request the reasoning behind this problem.

**Comment by neon-age** [comment]
Here's a little nasty, temporary workaround for it:
![image](https://user-images.githubusercontent.com/29812914/100089627-92e56500-2e84-11eb-9517-32cfdf228924.png)

I hope noone builds games for x32 machines these days, eh?

**Comment by neon-age** [comment]
Oh freak, it actually doesn't work, because Unity always builds for x32 :(
I guess I'll have to make it even nastier:
![image](https://user-images.githubusercontent.com/29812914/100090714-2ec3a080-2e86-11eb-8a05-0f9914847420.png)
