### ISSUE TITLE
Preferences UI doesn't work when plugin is located in Assets

### ISSUE THREAD

**Issue by Thane5** [neon-age/Smart-Hierarchy#8]
I just downloaded a zip of the repo to test the latest changes and dragged the folder into my Unity project, but it created an [error in the console](https://gist.github.com/Thane5/49780927cd5d7e7dc8b0d207769cbe6f).
The Menu entry in the preferences exists, but when i select it this error pops up.
I previously used the package manager, and modified the cache files to update it locally, so i didn't run into the issue before.

**Comment by neon-age** [comment]
If you want to make the package editable, just move it into Packages folder. The path to UI assets is currently hardcoded, so that's why an error occurs (can be fixed by using GUIDs instead)
