### ISSUE TITLE
Deleting script cause overflow

### ISSUE THREAD

**Issue by Mugiban** [neon-age/Smart-Hierarchy#9]
When deleting a script that is attached to a gameobject in the hierarchy, it cause a null reference exception and force you to restart unity.
Of course you are really not forced to restart if you disable and enable smart hierarchy from preferences.

Really good asset btw.
![Captura de pantalla 2020-12-12 004310](https://user-images.githubusercontent.com/23194808/101965574-6ddb4b00-3c15-11eb-967a-a5112dc57ff4.png)

**Comment by neon-age** [comment]
Have you got this issue on the latest version? I can't seem to reproduce this

**Comment by Mugiban** [comment]
Well I was testing and the problem was i had  smart hierarchy in Assets folder instead of Packages. When it is inside the Packages folder the problem does not happen. 
I should have tested this before... I guess you can close this issue.

**Comment by neon-age** [comment]
Just checked it in Assets, the latest version works fine
